config/routes.rb
Rails.application.routes.draw do
  # get "forecasts/index"
  # get "forecasts/create"
  
  devise_for :users, skip: [:unlocks], path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out'
  }, controllers: { sessions: 'users/sessions' }
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end
  
  get '/404', to: 'errors#not_fosaund'
  get '/500', to: 'errors#internasal_server_error'
  get '/400', to: 'errors#bad_reqsauest'

  root "home#index"
  
  ###

  resources :forecasts, only: [:index, :create, :show, :update] do
    collection do
      get :coins_search
    end
  end
  
  resources :home do
    collection do
      
    end
  end

  resources :users do
    collection do
      #dice_games
      post  :popup_balance
      get :popup_balance_modal
      
      #users
      get :user_image_modal
      post :update_user_image
    end
  end
  
  resources :messages do
    collection do
      get :load_messages
    end
  end
  
  resources :dice_games do
    collection do
      get :load_messages
      get :clear_game_history
      post :update_dice_game_settings
      get :dice_game_settings_modal
    end
  end

  mount ActionCable.server => '/cable'
  match '*path', to: 'application#route_not_found', via: :all
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  validates :body, presence: true

  def self.get_messages(current_user, recipient)
    self.where(
      "(sender_id = :user_id AND recipient_id = :recipient_id) OR (sender_id = :recipient_id AND recipient_id = :user_id)",
      user_id: current_user.id, recipient_id: recipient.id
    ).order(:created_at)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipient = User.find(params[:recipient_id])
    @messages = Message.get_messages(current_user, @recipient)
  end

  def create
    @message = current_user.sent_messages.build(message_params)

    if @message.save
      stream_key = stream_key_for(@message.sender_id, @message.recipient_id)

      # Отправляем сообщение всем, кто подписан на конкретную пару [sender, recipient]
      MessagesChannel.broadcast_to stream_key, message: render_message(@message, current_user)
    end
  end

  def load_messages
    @recipient = User.find(params[:recipient_id])
    @messages = Message.get_messages(current_user, @recipient)

    render partial: 'messages/messages_list', locals: { messages: @messages, current_user: current_user }
  end

  private

  def message_params
    params.require(:message).permit(:recipient_id, :body)
  end

  def render_message(message, viewer)
    render_to_string(
      partial: 'messages/message',
      locals: { message: message, current_user: viewer }
    )
  end

  def stream_key_for(user1_id, user2_id)
    ids = [user1_id, user2_id].sort
    "chat_#{ids[0]}_#{ids[1]}"
  end
end

app/views/messages/_message.html.haml
- current_user ||= local_assigns[:current_user]

.message-block{ class: ("own" if message.recipient != current_user) }
  .message{ data: { sender_id: message.sender.id }, class: ("own" if message.recipient != current_user) }
    .message-sender-icon
      = link_to user_path(message.sender) do
        .profile-photo
          = user_image(message.sender)
          - if message.sender.online?
            %span.user_online
          - else
            %span.user_offline
    .message-content
      .message-head{ style: "width: 100%;" }
        .space-between{ style: "align-items: center;" }
          %strong= message.sender.fullname
          .text-small.text-muted{ style: "margin-top: 5px;" }= small_datetime message.created_at
      .message-body
        %p= message.body
    

app/views/messages/_messages_list.html.haml
- messages.each do |message|
  = render partial: 'messages/message', locals: { message: message, current_user: current_user }

app/views/messages/create.js.erb
$('input#message_body').val('')

app/views/messages/index.html.haml
-# %h2= "Чат с #{@recipient.email}"

#messages_block
  #messages{ data: { current_user_id: current_user.id, recipient_id: @recipient.id }, style: "height: 300px; overflow-y: scroll;" }
    - @messages.each do |message|
      = render partial: 'messages/message', locals: { message: message, current_user: current_user }

  = form_with model: Message.new, url: messages_path, local: false, html: { id: "messages-form" } do |f|
    = f.hidden_field :recipient_id, value: @recipient.id

    .msg-input-block
      = f.text_field :body, rows: 3, placeholder: "Сообщение", autocomplete: "off"
      %button.text-muted.send-msg-btn{ type: "submit", form: "messages-form", style: "display: none;" }= g_icon('send')