config/routes.rb
Rails.application.routes.draw do
  # get "forecasts/index"
  # get "forecasts/create"
  
  devise_for :users, skip: [:unlocks], path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out'
  }, controllers: { sessions: 'users/sessions' }
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end
  
  get '/404', to: 'errors#not_fosaund'
  get '/500', to: 'errors#internasal_server_error'
  get '/400', to: 'errors#bad_reqsauest'

  root "home#index"
  
  ###

  resources :forecasts, only: [:index, :create, :show, :update] do
    collection do
      get :coins_search
    end
  end
  
  resources :home do
    collection do
      
    end
  end

  resources :users do
    collection do
      #dice_games
      post  :popup_balance
      get :popup_balance_modal
      
      #users
      get :user_image_modal
      post :update_user_image
    end
  end
  
  resources :messages do
    collection do
      get :load_messages
    end
  end
  
  resources :dice_games do
    collection do
      get :load_messages
      get :clear_game_history
      post :update_dice_game_settings
      get :dice_game_settings_modal
    end
  end

  mount ActionCable.server => '/cable'
  match '*path', to: 'application#route_not_found', via: :all
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id, dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id, dependent: :destroy

  has_many :dice_games
  has_many :dice_game_settings

  SUPER_USERS_LIST = ['dev', 'ceo']

  def self.get_roles
    [['Разработчик', 'dev'], ['Пользователь', 'user'], ['ТЕСТ', 'test'], ['Трейдер', 'crypto_trader']]
  end

  def auto_play_bet_amount
    user_dice_game_settings = DiceGameSetting.find_by(user_id: self.id)
    if user_dice_game_settings
      user_dice_game_settings.auto_play_bet_amount
    else
      nil
    end
  end

  def has_change_rights?(user)
    user.dev? || self == user
  end

  def fullname
    if firstname.present? && lastname.present?
      firstname == lastname ? firstname : "#{firstname} #{lastname}"
    elsif lastname.present?
      lastname
    elsif firstname.present?
      firstname
    else
      "unnamed"
    end
  end

  def make_user_image_file(image_file)
    return unless image_file

    if image_name.present?
      old_path = Rails.root.join("public", "user_images", image_name)
      File.delete(old_path) if File.exist?(old_path)
      update(image_name: nil)
    end

    file_id = (Time.now.to_f * 1000).to_i
    new_name = "user_image_#{file_id}_#{id}#{File.extname(image_file.original_filename).downcase}"
    path = Rails.root.join("public", "user_images", new_name)

    File.open(path, 'wb') { |file| file.write(image_file.read) }
    update(image_name: new_name)
  end

  def user_image_url
    if image_name.present? && File.exist?(Rails.root.join("public", "user_images", image_name))
      "/user_images/#{image_name}"
    else
      default_user_image
    end
  end

  def cover_picture
    
  end

  def user_login_id
    "(#{self.role}) ##{self.id}"
  end

  def profile_id
    "#{self.email} ##{self.id}"
  end

  def online?
    OnlineTracker.online?(self.id)
  end

  def default_user_image
    "/user_images/default_user_image.webp"
  end

  def has_user_image_file?
    image_name.present? && File.exist?(Rails.root.join("public", "user_images", image_name))
  end

  def registered_info
    "Зарегистрирован #{ApplicationController.helpers.small_date(created_at)}"
  end

  def user_role_id
    "(#{role}) ##{id}"
  end

  def valid_balance_for_dice?(bet_amount)
    balance.to_f >= bet_amount.to_f
  end

  def popup_user_balane(balance)
    update(balance: balance.to_f + self.balance.to_f)
  end

  def change_balance_by_dice(total_balance)
    update(balance: total_balance)
  end

  def dev?
    role == 'dev'
  end

  def crypto_trader?
    role == 'crypto_trader'
  end

  def user?
    role == 'user'
  end

  def test?
    role == 'test'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    super do |user|
      #отметить пользователя онлайн
      OnlineTracker.mark_online(user) if user.present?
    end

    if session[:prev_cur_url].present? && current_user
      redirect_to session[:prev_cur_url]
    end
  end

  def destroy
    super do |user|
      # отметить пользователя оффлйн
      OnlineTracker.mark_offline(current_user) if current_user.present?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :check_super_user_access, only: %i[ edit update create destroy ]
  def index
    @users = User.all
    @user = User.new
  end

  def show

  end

  def popup_balance
    user_id = params.dig(:user, :id)
    balance = params.dig(:user, :balance)

    @user = User.find_by_id(user_id)
    if @user
      @balance_updated = @user.popup_user_balane(balance)

    else
      flash[:danger] = "Пользователь не найден"
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Пользователь успешно создан.'
    else
      @users = User.all 
      render :index
    end
  end
  
  def update

    filtered_params = user_params

    if filtered_params[:password].blank?
      filtered_params = filtered_params.except(:password, :password_confirmation)
    end

    if @user.update(filtered_params)
      flash[:success] = "Данные обновлены"
    else
      flash[:danger] = "Произошла ошибка"
    end

    redirect_to edit_user_path(@user)
  end

  def edit

  end

  def destroy
    if @user.destroy
      flash[:success] = "Пользователь удалён"
    else
      flash[:danger] = "Ошибка при удалении пользователя"
    end
    redirect_to users_path
  end

  def update_user_image
    file = params[:user_image_file]
    if file.present? && @user.present?
      @updated = @user.make_user_image_file(file)
    else
      @updated = false
    end

    respond_to do |format|
      format.html { redirect_to user_path(@user) } # для обычных запросов
      format.js   # отрендерит update_user_image.js.erb
    end
  end

  def user_image_modal
    user_id = params[:user_id]
    @user = User.find_by_id(user_id)
  end

  def popup_balance_modal
    user_id = params[:user_id]
    @user = User.find_by_id(user_id)
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    # Обрати внимание: :password_confirmation, а не :confirm_password
    params.require(:user).permit(:firstname, :lastname, :role, :email, :password, :password_confirmation, :balance)
  end
end

app/views/users/_form.html.haml
- can_change = @user.has_change_rights?(current_user)

.form-fields.filled-block
  = form_for @user, html: { id: 'user-form' } do |f|
    .row
      .col-md-6
        .field
          = f.label "Имя"
          = f.text_field :firstname, placeholder: "Имя", required: false, autocomplete: "new-password", required: true
      .col-md-6
        .field
          = f.label "Фамилия"
          = f.text_field :lastname, placeholder: "Фамилия", required: false, autocomplete: "new-password"
    .row
      .col-md-12
        .field
          = f.label "Почта"
          = f.text_field :email, placeholder: "Почта", type: :email, required: false, autocomplete: "new-password", required: true
    .row
      .col-md-6
        .field
          = f.label "Пароль"
          = f.password_field :password, placeholder: "Пароль", autocomplete: "new-password", required: !@user.id.present?
      .col-md-6
        .field
          = f.label "Подтверждение пароля"
          = f.password_field :password_confirmation, placeholder: "Подтверждение пароля", autocomplete: "new-password", required: !@user.id.present?
    .row
      .col-md-12
        .field
          = f.label "Роль"
          = f.select :role, User.get_roles, {}, class: "form-control", required: true, include_blank: true
    -# .row
    -#   .col-md-12
    -#     .field
    -#       = f.label "Баланс"
    -#       = f.number_field :balance, step: 0.01, class: "form-control"
    - if can_change && !@user.id.present?
      = f.submit (@user.new_record? ? "Создать" : "Обновить"), class: "btn btn-primary mt-3", style: "width: 100%;"

app/views/users/_popup_user_balance_modal.html.haml
= form_with model: user, url: popup_balance_users_path, method: :post, local: false, html: { id: "popup_user_balance" } do |f|
  = f.hidden_field :id

  .flex-row{ style: "align-items: baseline;" }
    = f.number_field :balance, value: nil, required: true, step: 0.01, min: 0.01, placeholder: 'Введите сумму'
    - if DiceGame.all.length > 0
      -# .small-btn.gradient-hover.btn#get_last_bet_amount.text-small{ style: "white-space: nowrap; height: 29px; align-items: center;" } Последняя ставка

app/views/users/_user_image_modal.html.haml
= form_with url: "/users/update_user_image", method: :post, multipart: true, id: "update_user_image", local: false do |f|
  %label{ for: "user_image" } Загрузить фото
  = f.file_field :user_image_file
  = f.hidden_field :user_id, value: user ? user.id : nil

app/views/users/edit.html.haml
.row
  .col-md-12
    .edit-user-title.content-panel-header
      = link_to user_path(@user), class: "btn small-btn gradient-hover", style: "margin-right: 15px;" do
        = fa_icon "arrow-left"
      .space-between{ style: "align-items: center;" }
        %div
          %span.text-xxl.text-bold Редактировать пользователя
        %div
          %button.btn-primary.small-btn.gradien-hover{ type: 'submit', form: 'user-form' }
            %span.hide-on-mobile= "Сохранить"
            = g_icon("check")
    = render 'form'

app/views/users/index.html.haml
.flex-block
  %div
    .table-block.users-table.with-hidden-scrollbar
      %table.big-table
        %thead
          %tr
            %th.text-muted #
            %th
            %th Имя
            %th Фамилия
            %th email
            %th Роль
            %th Баланс
            %th 
            -# %th 
            - if current_user.dev?
              %th 
        %tbody
          - @users.each do |user|
            %tr
              %td.text-muted= user.id
              %td
                = link_to user_path(user) do
                  .profile-photo
                    = user_image(user)
                    - if user.online?
                      %span.user_online
                    - else
                      %span.user_offline
              %td= user.firstname
              %td= user.lastname ? user.lastname : '-'
              %td= user.email
              %td= user.role
              %td= user.balance.round(2)
              %td
              -# %td
              -#   = link_to user_path(user) do
              -#     .btn.mini-btn.gradient-hover= g_icon 'visibility'
              - if current_user.dev?
                %td
                  = link_to edit_user_path(user) do
                    .btn.mini-btn.gradient-hover= g_icon 'edit'

  - if current_user.dev?
    %div{ style: "width: 100%;" }
      = render 'form'

app/views/users/popup_balance.js.erb
<% if @balance_updated %>
  $('span#user_balance').html('<%= format_number @user.balance.to_f.round(2) %>')
  $('span#user_balance').attr('data-balance', '<%= @user.balance.to_f %>')
  modalShowByResult(true)
<% else %>
  modalShowByResult(false)
<% end %>

app/views/users/popup_balance_modal.js.erb
modalShow("<%= j render partial: 'popup_user_balance_modal', locals: { user: @user } %>", "Пополнить баланс", "popup_user_balance")

$('input#user_balance').focus()

app/views/users/show.html.haml
- can_change = @user.has_change_rights?(current_user)

.user-info-panel
  #user_id{ style: "display: none !important;" }= @user.id
  .back-to-users
    - user_back_link = can_change ? users_path : root_path

    .space-between.content-panel-header
      %div
        = link_to user_back_link, class: "btn small-btn gradient-hover", style: "margin-right: 15px;" do
          = fa_icon "arrow-left"
        - if !@user.online?
          %span.text-muted= "Последний раз был в сети #{small_datetime @user.current_sign_in_at}" if @user.current_sign_in_at
      - if can_change || current_user == @user
        = link_to edit_user_path(@user) do
          .small-btn.btn-primary= g_icon 'edit'
  .profile-cover
    = @user.cover_picture
  .profile-body
    .profile-picture
      .user-avatar
        .profile-image-block{ class: can_change ? "update-user-image" : '', data: { user_id: @user.id } }
          = user_image(@user)
    .user-desc
      .space-between{ style: "width: 100%;" }
        %div
          = @user.firstname
          %span.hide-on-laptop= @user.lastname
        - if @user != current_user
          = link_to messages_path(recipient_id: @user.id) do
            .btn.small-btn.chat-user-btn= g_icon("chat_bubble")
      #user-id.text-muted.text-big= @user.user_login_id

    .user-registered-info
      .text-muted= @user.registered_info

app/views/users/update.js.erb
console.log('<%= @params %>')
console.log('<%= @updated %>')

app/views/users/update_user_image.js.erb
alert(1)

app/views/users/user_image_modal.js.erb
modalShow("<%= j render partial: 'user_image_modal', locals: { user: @user } %>", "Изменить фото", "update_user_image")