config/routes.rb
Rails.application.routes.draw do
  # get "forecasts/index"
  # get "forecasts/create"
  
  devise_for :users, skip: [:unlocks], path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out'
  }, controllers: { sessions: 'users/sessions' }
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end
  
  get '/404', to: 'errors#not_fosaund'
  get '/500', to: 'errors#internasal_server_error'
  get '/400', to: 'errors#bad_reqsauest'

  root "home#index"
  
  ###

  resources :forecasts, only: [:index, :create, :show, :update] do
    collection do
      get :coins_search
    end
  end
  
  resources :home do
    collection do
      
    end
  end

  resources :users do
    collection do
      #dice_games
      post  :popup_balance
      get :popup_balance_modal
      
      #users
      get :user_image_modal
      post :update_user_image
    end
  end
  
  resources :messages do
    collection do
      get :load_messages
    end
  end
  
  resources :dice_games do
    collection do
      get :load_messages
      get :clear_game_history
      post :update_dice_game_settings
      get :dice_game_settings_modal
    end
  end

  mount ActionCable.server => '/cable'
  match '*path', to: 'application#route_not_found', via: :all
end

app/models/dice_game.rb
class DiceGame < ApplicationRecord
  belongs_to :user

  validates :bet_amount, presence: true, numericality: { greater_than: 0 }
  validates :chance, presence: true, inclusion: { in: 1..99 }

  RESULT_WIN = 'win'
  RESULT_LOSE = 'lose'
  RESULT_DRAW = 'draw'

  def self.get_history(user=nil, show=25)
    if user
      self.where(user_id: user.id).last(show).reverse
    else
      self.last(25).reverse
    end
  end

  def self.play!(chance, user, bet_amount)
    return unless user.valid_balance_for_dice?(bet_amount)
  
    total_balance = user.balance
    roll_result = rand(1..100)
    multiplier = 100 / chance
  
    if roll_result <= chance
      game_result = RESULT_WIN
      win_amount = (bet_amount * multiplier) - bet_amount
      total_balance += win_amount
    elsif roll_result >= chance
      game_result = RESULT_LOSE
      lose_amount = bet_amount
      total_balance -= bet_amount
    else
      game_result = RESULT_DRAW
    end
  
    game = self.create_game_result(user, chance, bet_amount, win_amount || 0, lose_amount || 0, roll_result, game_result)
    user.change_balance_by_dice(total_balance)
    game
  end

  def self.create_game_result(user=nil, chance=nil, bet_amount=nil, win_amount=nil, lose_amount=nil, roll_result=nil, game_result=nil)
    self.create(user_id: user.id, chance: chance, 
      bet_amount: bet_amount, win_amount: win_amount, 
      lose_amount: lose_amount, roll_result: roll_result, 
      game_result: game_result)
  end

  def win?
    self.game_result == RESULT_WIN
  end
  
  def lose?
    self.game_result == RESULT_LOSE
  end
  
  def draw?
    self.game_result == RESULT_DRAW
  end

end

app/controllers/dice_games_controller.rb
class DiceGamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @dice_game = DiceGame.new()
    @history = DiceGame.get_history(current_user)

  end
  
  def clear_game_history
    @cleared = DiceGame.where(user_id: current_user.id).delete_all 
    if @cleared
      @history = DiceGame.get_history(current_user)
    end
  end

  def update_dice_game_settings
    @updated = DiceGameSetting.create_settings(current_user, params)
  end

  def dice_game_settings_modal

  end

  def create
    @bet_amount = dice_params[:bet_amount].to_f
    @chance = dice_params[:chance].to_f

    if @bet_amount > 0
      @game_played = DiceGame.play!(@chance, current_user, @bet_amount)
      @history = DiceGame.get_history(current_user)
    end
  end

  private

  def dice_params
    params.require(:dice_game).permit(:chance, :bet_amount)
  end


end

app/views/dice_games/_dice_game_settings_modal.html.haml
= form_with url: update_dice_game_settings_dice_games_path, method: :post, local: false, html: { id: "dice_games_settings" } do |f|
  = f.label :auto_play_bet_amount, "Выберите ставку для автоигры"
  = f.number_field :auto_play_bet_amount, value: nil, required: true, step: 0.01, min: 0.01, placeholder: 'Введите автоставку', value: current_user.auto_play_bet_amount

app/views/dice_games/_games_history.html.haml
.table-block.with-hidden-scrollbar-y
  .space-between{ style: "margin-bottom: 20px; align-items: center;" }
    %span История
    = link_to clear_game_history_dice_games_path, remote: true do
      %span.btn.small-btn.gradient-hover= g_icon 'delete_history'
  %table.big-table
    %thead
      %tr
        %th.text-muted #
        %th Ставка
        %th Шанс
        %th Выпало
        %th Результат
        -# %th Дата
    %tbody
      - i = 0
      - history.each do |game|
        - i += 1
        %tr
          %td.text-muted
            = game.id
          %td.last-bet-amount{ data: { last_bet_amount: game.bet_amount } }
            = format_number game.bet_amount
          %td= "#{game.chance}%"
          %td= game.roll_result
          %td#win_lose_result{ data: { win_lose: game.win? ? 'win' : 'lose' } }
            - if game.win?
              - profit = format_number game.win_amount.round(2)
              .text-success= "+#{profit}"
            - else
              - loss = format_number game.lose_amount.round(2)
              .text-danger= "-#{loss}"
          -# %td= small_datetime(game.created_at)

app/views/dice_games/_new_game.html.haml
.filled-block
  .space-between{ style: "align-items: start;" }
    %strong.text-big{ style: "display: flex; align-items: center; gap: 5px;" }
      %button.small-btn.btn.gradient-hover.dice-game-settings{ type: "button", data: { auto_play_bet_amount: current_user.auto_play_bet_amount ? current_user.auto_play_bet_amount : 0 } }
        = g_icon('settings')
    .dice-balance.text-right 
      Баланс:
      %span#user_balance{ data: { balance: current_user.balance.to_f } }
        = format_number current_user.balance.to_f.round(2)
      - if current_user.dev?
        %span.mini-btn.gradient-hover.btn#popup-user-balance{ data: { user_id: current_user.id } }
          = g_icon 'add'

  = form_for @dice_game, remote: true, html: { id: "dice_form" } do |f|

    .row.reverse-row-mobile{ style: "gap: 30px;" }
      .col-md-6
        %div.bet-amount
          .flex-row
            %div{ style: "width: 100%;" }
              .field
                = f.label :bet_amount, "Ставка"
                .flex-row{ style: "align-items: center;" }
                  = f.number_field :bet_amount, step: 0.01, min: 0.01, id: "bet_amount"
                  %div{ style: "white-space: nowrap;" }
                    .small-btn.gradient-hover.btn#all_in_button{ type: "button" } All In

          %div.flex-row{ style: "margin-top: 5px;" }
            %button.small-btn.btn.gradient-hover.bet-action{ type: "button", data: { action: "half" } } /2
            %button.small-btn.btn.gradient-hover.bet-action{ type: "button", data: { action: "one_point_five" } } /1.5
            %button.small-btn.btn.gradient-hover.bet-action{ type: "button", data: { action: "double" } } x2
            %button.small-btn.btn.gradient-hover.bet-action{ type: "button", data: { action: "point_one_five" } } x1.5

        %div.flex-row
          %button#play_button.btn.medium-btn.gradient-hover{ type: "submit", form: "dice_form", style: "margin-top: 10px; width: 100%;" }="Бросить"
          %button.btn.medium-btn.btn-primary.autoplay_bot{ type: "button", form: "dice_form", style: "margin-top: 10px; width: fit-content;" }= g_icon('smart_toy')

      .col-md-6
        -# = render partial: "result_container"
        #result_container
          %h3 Результат броска:
          #animation_container
            #chance_bar
            #roll_marker
          %p#roll_text
          %p#win_text
        %div.chance-section
          %span
            %span Шанс выигрыша
            %span#chance_value 50%
          %input#chance_input{ type: "number", min: 1, max: 99, value: 50, class: "chance-number" }
          = f.range_field :chance, min: 1, max: 99, value: 50, id: "chance_range"

          %div.chance-presets
            .mini-btn.btn.gradient-hover.chance-preset{ data: { chance: 10 } } 10%
            .mini-btn.btn.gradient-hover.chance-preset{ data: { chance: 25 } } 25%
            .mini-btn.btn.gradient-hover.chance-preset{ data: { chance: 50 } } 50%
            .mini-btn.btn.gradient-hover.chance-preset{ data: { chance: 75 } } 75%

app/views/dice_games/_result_container.html.haml
#result_container
  %h3 Результат броска:
  #animation_container
    #chance_bar
    #roll_marker
  %p#roll_text
  %p#win_text

app/views/dice_games/clear_game_history.js.erb
<% if @cleared %>
  modalShowByResult(true)
  $('#games_history_container').html("<%= j render partial: 'games_history', locals: { history: @history } %>");

<% else %>
  modalShowByResult(false)
<% end %>

app/views/dice_games/create.js.erb
<% if @bet_amount > 0 %>

  <% if @game_played %>
    <% if @game_played.win? %>
      toastr.success('Вы выиграли')
    <% end %>
    <% if @game_played.lose? %>
      toastr.danger('Вы проиграли')
    <% end %>
    <% if @game_played.draw? %>
      toastr.primary('Ничья')
    <% end %>
    $('#user_balance').text("<%= format_number current_user.balance.to_f.round(2) %>");
    $('span#user_balance').attr('data-balance', '<%= current_user.balance.to_f %>')
    $('#result_container').show();
    $('#roll_marker').css('left', '<%= @game_played.roll_result %>%');
    $('#roll_text').text('Выпало: <%= @game_played.roll_result %>');

    $('#games_history_container').html("<%= j render partial: 'games_history', locals: { history: @history } %>");
  <% else %>
    toastr.danger('Недостаточно средств.');
  <% end %>
<% end %>

app/views/dice_games/dice_game_settings_modal.js.erb
modalShow("<%= j render partial: 'dice_game_settings_modal', locals: { user: @user } %>", "Стратегия Х2", "dice_games_settings")

app/views/dice_games/index.html.haml
.row
  .col-md-6
    .dice-block
      %div
        = render partial: "new_game"
      %div
        #games_history_container
          = render partial: "games_history", locals: { history: @history }

app/views/dice_games/update_dice_game_settings.js.erb
<% if @updated %>
  $('.dice-game-settings').attr('data-auto-play-bet-amount', '<%= current_user.auto_play_bet_amount ? current_user.auto_play_bet_amount : 0 %>')
  modalShowByResult(true)
<% else %>
  modalShowByResult(false)
<% end %>