config/routes.rb
Rails.application.routes.draw do
  # get "forecasts/index"
  # get "forecasts/create"
  
  devise_for :users, skip: [:unlocks], path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out'
  }, controllers: { sessions: 'users/sessions' }
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end
  
  get '/404', to: 'errors#not_fosaund'
  get '/500', to: 'errors#internasal_server_error'
  get '/400', to: 'errors#bad_reqsauest'

  root "home#index"
  
  ###

  resources :forecasts, only: [:index, :create, :show, :update] do
    collection do
      get :coins_search
    end
  end
  
  resources :home do
    collection do
      
    end
  end

  resources :users do
    collection do
      #dice_games
      post  :popup_balance
      get :popup_balance_modal
      
      #users
      get :user_image_modal
      post :update_user_image
    end
  end
  
  resources :messages do
    collection do
      get :load_messages
    end
  end
  
  resources :dice_games do
    collection do
      get :load_messages
      get :clear_game_history
      post :update_dice_game_settings
      get :dice_game_settings_modal
    end
  end

  mount ActionCable.server => '/cable'
  match '*path', to: 'application#route_not_found', via: :all
end

app/views/layouts/_header.html.haml
.header
  .flex-row{ style: "align-items: center;" }
    %div{ style: "display: flex; align-items: center; gap: 10px;" }
      - if current_user
        %button#sidebar-toggle.menu-btn.show-on-mobile= g_icon 'dehaze'
    -# .logo.hide-on-mobile
    -#   = link_to root_path do
    -#     .logo-block
    -#       .logo-icon
    -#         = logo_icon
  .user-info
    - if current_user.present?
      .flex-row-center
        = link_to user_path(current_user) do
          .user-block
            .header-profile-photo
              = user_image current_user
              %span.user_online
            %div
              = current_user.fullname
              .text-muted.text-small= current_user.user_role_id
        %div
          = link_to sign_out_path, method: :delete do
            = g_icon 'logout'
    - else
      = link_to sign_in_path do
        -# Войти
        = g_icon 'login'

app/views/layouts/_sidebar.html.haml
.side-bar-menu
  %div
    = link_to root_path do
      .sidebar-header.text-center
        .logo-block{ style: "justify-content: center;" }
          .logo-icon
            = logo_icon
    .side-bar-main-menu.with-hidden-scrollbar-y
      .nav-items
        .nav
          = link_to users_path do
            .nav-item{ class: active_sidebar?(users_path) ? 'active' : 'inactive' }
              = g_icon(:group)
              %strong= "Пользователи"
          
        - if current_user && current_user.dev?
          .nav
            = link_to dice_games_path do
              .nav-item{ class: active_sidebar?(dice_games_path) ? 'active' : 'inactive' }
                = g_icon(:casino)
                %strong= "Кости"

        - if current_user && current_user.crypto_trader? || current_user && current_user.dev?
          .nav
            = link_to forecasts_path do
              .nav-item{ class: active_sidebar?(forecasts_path) ? 'active' : 'inactive' }
                = g_icon("currency_bitcoin")
                %strong= "Прогноз"

  .side-bar-dop-menu
    .nav-items
      .nav
        = link_to "#" do
          .nav-item{ class: active_sidebar?('#') ? 'active' : 'inactive' }
            = g_icon(:settings)
            %strong= "Настройки"
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Vexodus
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover, user-scalable=no" }
    %meta{ name: "mobile-web-app-capable", content: "yes" }
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }
    %meta{ name: "apple-mobile-web-app-status-bar-style", content: "black-translucent" }
    %meta{ name: "apple-mobile-web-app-title", content: "Vexodus" }
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    %link{ rel: "manifest", href: "/manifest.json" }
    %link{ rel: "icon", href: "/icons/vexodus_mini.png", type: "image/png" }
    %link{ rel: "apple-touch-icon", sizes: "180x180", href: "/icons/vexodus_mini.png" }
    %link{ rel: "apple-touch-icon", sizes: "152x152", href: "/icons/vexodus_mini.png" }
    %link{ rel: "apple-touch-icon", sizes: "120x120", href: "/icons/vexodus_mini.png" }
    %link{ href: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined", rel: "stylesheet" }
    %link{ href: "https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css", rel: "stylesheet" }

    / Подключаем jquery и select2 без defer, чтобы сразу доступны были
    %script{ src: "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" }
    %script{ src: "https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" }

    / Подключаем Chart.js, date-fns-адаптер и financial plugin
    %script{ src: "https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js" }
    / Адаптер для работы с временными шкалами (внутри содержит date-fns)
    %script{ src: "https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@2.0.0/dist/chartjs-adapter-date-fns.bundle.min.js" }
    / Финансовые графики (свечи, бары)
    %script{ src: "https://cdn.jsdelivr.net/npm/chartjs-chart-financial@0.2.1/dist/chartjs-chart-financial.min.js" }

    / Подключаем основной application.js через asset pipeline с defer
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

  %body
    .body-container
      - if current_user
        #sidebar
          = render partial: "layouts/sidebar"
        #sidebar-overlay.hidden

      .app-container
        .app-header
          = render partial: "layouts/header"
        .app-body
          .content
            = yield

#flash-container
  - flash.each do |type, message|
    %div{ class: "flash #{type}" }= message